//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleRWSProject.ORD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.metcash.com/RetailWebService/", ConfigurationName="ORD.RetailWebService")]
    public interface RetailWebService {
        
        // CODEGEN: Generating message contract since the operation placeWSOrder is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/RetailWebServices/SharedResources/Schema/Ash2WSDL/RetailWebService-service0.serv" +
            "iceagent/RetailWebServiceEndpoint0/placeWSOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.ORD.placeWSOrderResponse1 placeWSOrder(SampleRWSProject.ORD.placeWSOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tibco.integration.metcash.com/")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string b2BAccountField;
        
        private string passwordField;
        
        private string customerIdField;
        
        private string stateCodeField;
        
        private string pillarIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string B2BAccount {
            get {
                return this.b2BAccountField;
            }
            set {
                this.b2BAccountField = value;
                this.RaisePropertyChanged("B2BAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PillarId {
            get {
                return this.pillarIdField;
            }
            set {
                this.pillarIdField = value;
                this.RaisePropertyChanged("PillarId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tibco.integration.metcash.com/")]
    public partial class placeWSOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tibco.integration.metcash.com/")]
    public partial class placeWSOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wSOrderField;
        
        private string orderTypeField;
        
        private string sourceServiceField;
        
        private string serviceIdField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WSOrder {
            get {
                return this.wSOrderField;
            }
            set {
                this.wSOrderField = value;
                this.RaisePropertyChanged("WSOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SourceService {
            get {
                return this.sourceServiceField;
            }
            set {
                this.sourceServiceField = value;
                this.RaisePropertyChanged("SourceService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ServiceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("ServiceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class placeWSOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.tibco.integration.metcash.com/")]
        public SampleRWSProject.ORD.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tibco.integration.metcash.com/", Order=0)]
        public SampleRWSProject.ORD.placeWSOrder placeWSOrder;
        
        public placeWSOrderRequest() {
        }
        
        public placeWSOrderRequest(SampleRWSProject.ORD.Authentication Authentication, SampleRWSProject.ORD.placeWSOrder placeWSOrder) {
            this.Authentication = Authentication;
            this.placeWSOrder = placeWSOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class placeWSOrderResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tibco.integration.metcash.com/", Order=0)]
        public SampleRWSProject.ORD.placeWSOrderResponse placeWSOrderResponse;
        
        public placeWSOrderResponse1() {
        }
        
        public placeWSOrderResponse1(SampleRWSProject.ORD.placeWSOrderResponse placeWSOrderResponse) {
            this.placeWSOrderResponse = placeWSOrderResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RetailWebServiceChannel : SampleRWSProject.ORD.RetailWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RetailWebServiceClient : System.ServiceModel.ClientBase<SampleRWSProject.ORD.RetailWebService>, SampleRWSProject.ORD.RetailWebService {
        
        public RetailWebServiceClient() {
        }
        
        public RetailWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetailWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.ORD.placeWSOrderResponse1 SampleRWSProject.ORD.RetailWebService.placeWSOrder(SampleRWSProject.ORD.placeWSOrderRequest request) {
            return base.Channel.placeWSOrder(request);
        }
        
        public SampleRWSProject.ORD.placeWSOrderResponse placeWSOrder(SampleRWSProject.ORD.Authentication Authentication, SampleRWSProject.ORD.placeWSOrder placeWSOrder1) {
            SampleRWSProject.ORD.placeWSOrderRequest inValue = new SampleRWSProject.ORD.placeWSOrderRequest();
            inValue.Authentication = Authentication;
            inValue.placeWSOrder = placeWSOrder1;
            SampleRWSProject.ORD.placeWSOrderResponse1 retVal = ((SampleRWSProject.ORD.RetailWebService)(this)).placeWSOrder(inValue);
            return retVal.placeWSOrderResponse;
        }
    }
}
