//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleRWSProject.RWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", ConfigurationName="RWS.IGAWebServices")]
    public interface IGAWebServices {
        
        // CODEGEN: Generating message contract since the operation areYouThere is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.RWS.areYouThereResponse1 areYouThere(SampleRWSProject.RWS.areYouThereRequest request);
        
        // CODEGEN: Generating message contract since the operation downloadAllInvoices is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.RWS.downloadAllInvoicesResponse downloadAllInvoices(SampleRWSProject.RWS.downloadAllInvoicesRequest request);
        
        // CODEGEN: Generating message contract since the operation listInvoices is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.RWS.listInvoicesResponse listInvoices(SampleRWSProject.RWS.listInvoicesRequest request);
        
        // CODEGEN: Generating message contract since the operation listHostFilesQueued is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.RWS.listHostFilesQueuedResponse1 listHostFilesQueued(SampleRWSProject.RWS.listHostFilesQueuedRequest request);
        
        // CODEGEN: Generating message contract since the operation getLastFileSent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.RWS.getLastFileSentResponse1 getLastFileSent(SampleRWSProject.RWS.getLastFileSentRequest request);
        
        // CODEGEN: Generating message contract since the operation getNextFileQueued is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.RWS.getNextFileQueuedResponse getNextFileQueued(SampleRWSProject.RWS.getNextFileQueuedRequest request);
        
        // CODEGEN: Generating message contract since the operation placeMailboxOrder is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.RWS.placeMailboxOrderResponse1 placeMailboxOrder(SampleRWSProject.RWS.placeMailboxOrderRequest request);
        
        // CODEGEN: Generating message contract since the operation getOrderSummary is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SampleRWSProject.RWS.getOrderSummaryResponse getOrderSummary(SampleRWSProject.RWS.getOrderSummaryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tpIdField;
        
        private string passwordField;
        
        private string customerIdField;
        
        private string stateCodeField;
        
        private string pillarIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TpId {
            get {
                return this.tpIdField;
            }
            set {
                this.tpIdField = value;
                this.RaisePropertyChanged("TpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PillarId {
            get {
                return this.pillarIdField;
            }
            set {
                this.pillarIdField = value;
                this.RaisePropertyChanged("PillarId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class OrderSummaryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class getOrderSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mailboxIdField;
        
        private string batchIdField;
        
        private string timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mailboxId {
            get {
                return this.mailboxIdField;
            }
            set {
                this.mailboxIdField = value;
                this.RaisePropertyChanged("mailboxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string batchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
                this.RaisePropertyChanged("batchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class getFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private metFile responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public metFile response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class metFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] convertedDataFileField;
        
        private string dataHandlerField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] convertedDataFile {
            get {
                return this.convertedDataFileField;
            }
            set {
                this.convertedDataFileField = value;
                this.RaisePropertyChanged("convertedDataFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dataHandler {
            get {
                return this.dataHandlerField;
            }
            set {
                this.dataHandlerField = value;
                this.RaisePropertyChanged("dataHandler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class getNextFileQueued : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class listInvoices : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mailboxidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mailboxid {
            get {
                return this.mailboxidField;
            }
            set {
                this.mailboxidField = value;
                this.RaisePropertyChanged("mailboxid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class listHostFilesQueuedResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private wsResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public wsResponse response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class wsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] filesField;
        
        private string messageField;
        
        private bool statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public object[] files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
                this.RaisePropertyChanged("files");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class listHostFilesQueued : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailbox.ws.integration.metcash.com/")]
    public partial class mailboxOrderAck : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string batchIdField;
        
        private string commentsField;
        
        private string timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string batchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
                this.RaisePropertyChanged("batchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class placeMailboxOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mailboxOrderAck orderSummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public mailboxOrderAck orderSummary {
            get {
                return this.orderSummaryField;
            }
            set {
                this.orderSummaryField = value;
                this.RaisePropertyChanged("orderSummary");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class placeMailboxOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mailboxOrderField;
        
        private string fileNameField;
        
        private string mailboxNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mailboxOrder {
            get {
                return this.mailboxOrderField;
            }
            set {
                this.mailboxOrderField = value;
                this.RaisePropertyChanged("mailboxOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mailboxNumber {
            get {
                return this.mailboxNumberField;
            }
            set {
                this.mailboxNumberField = value;
                this.RaisePropertyChanged("mailboxNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class getLastFileSentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private metFile responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public metFile response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class getLastFileSent : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class downloadAllInvoiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private wsResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public wsResponse response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class downloadAllInvoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mailboxIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mailboxId {
            get {
                return this.mailboxIdField;
            }
            set {
                this.mailboxIdField = value;
                this.RaisePropertyChanged("mailboxId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class areYouThereResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
    public partial class areYouThere : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class areYouThereRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SampleRWSProject.RWS.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.areYouThere areYouThere;
        
        public areYouThereRequest() {
        }
        
        public areYouThereRequest(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.areYouThere areYouThere) {
            this.authentication = authentication;
            this.areYouThere = areYouThere;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class areYouThereResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.areYouThereResponse areYouThereResponse;
        
        public areYouThereResponse1() {
        }
        
        public areYouThereResponse1(SampleRWSProject.RWS.areYouThereResponse areYouThereResponse) {
            this.areYouThereResponse = areYouThereResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadAllInvoicesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SampleRWSProject.RWS.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.downloadAllInvoice downloadAllInvoice;
        
        public downloadAllInvoicesRequest() {
        }
        
        public downloadAllInvoicesRequest(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.downloadAllInvoice downloadAllInvoice) {
            this.authentication = authentication;
            this.downloadAllInvoice = downloadAllInvoice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadAllInvoicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.downloadAllInvoiceResponse downloadAllInvoiceResponse;
        
        public downloadAllInvoicesResponse() {
        }
        
        public downloadAllInvoicesResponse(SampleRWSProject.RWS.downloadAllInvoiceResponse downloadAllInvoiceResponse) {
            this.downloadAllInvoiceResponse = downloadAllInvoiceResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listInvoicesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SampleRWSProject.RWS.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.listInvoices listInvoices;
        
        public listInvoicesRequest() {
        }
        
        public listInvoicesRequest(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.listInvoices listInvoices) {
            this.authentication = authentication;
            this.listInvoices = listInvoices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listInvoicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listInvoicesResponse", Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] listInvoicesResponse1;
        
        public listInvoicesResponse() {
        }
        
        public listInvoicesResponse(string[] listInvoicesResponse1) {
            this.listInvoicesResponse1 = listInvoicesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listHostFilesQueuedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SampleRWSProject.RWS.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.listHostFilesQueued listHostFilesQueued;
        
        public listHostFilesQueuedRequest() {
        }
        
        public listHostFilesQueuedRequest(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.listHostFilesQueued listHostFilesQueued) {
            this.authentication = authentication;
            this.listHostFilesQueued = listHostFilesQueued;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listHostFilesQueuedResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.listHostFilesQueuedResponse listHostFilesQueuedResponse;
        
        public listHostFilesQueuedResponse1() {
        }
        
        public listHostFilesQueuedResponse1(SampleRWSProject.RWS.listHostFilesQueuedResponse listHostFilesQueuedResponse) {
            this.listHostFilesQueuedResponse = listHostFilesQueuedResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastFileSentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SampleRWSProject.RWS.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.getLastFileSent getLastFileSent;
        
        public getLastFileSentRequest() {
        }
        
        public getLastFileSentRequest(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.getLastFileSent getLastFileSent) {
            this.authentication = authentication;
            this.getLastFileSent = getLastFileSent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastFileSentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.getLastFileSentResponse getLastFileSentResponse;
        
        public getLastFileSentResponse1() {
        }
        
        public getLastFileSentResponse1(SampleRWSProject.RWS.getLastFileSentResponse getLastFileSentResponse) {
            this.getLastFileSentResponse = getLastFileSentResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextFileQueuedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SampleRWSProject.RWS.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.getNextFileQueued getNextFileQueued;
        
        public getNextFileQueuedRequest() {
        }
        
        public getNextFileQueuedRequest(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.getNextFileQueued getNextFileQueued) {
            this.authentication = authentication;
            this.getNextFileQueued = getNextFileQueued;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextFileQueuedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.getFileResponse getFileResponse;
        
        public getNextFileQueuedResponse() {
        }
        
        public getNextFileQueuedResponse(SampleRWSProject.RWS.getFileResponse getFileResponse) {
            this.getFileResponse = getFileResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class placeMailboxOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SampleRWSProject.RWS.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.placeMailboxOrder placeMailboxOrder;
        
        public placeMailboxOrderRequest() {
        }
        
        public placeMailboxOrderRequest(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.placeMailboxOrder placeMailboxOrder) {
            this.authentication = authentication;
            this.placeMailboxOrder = placeMailboxOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class placeMailboxOrderResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.placeMailboxOrderResponse placeMailboxOrderResponse;
        
        public placeMailboxOrderResponse1() {
        }
        
        public placeMailboxOrderResponse1(SampleRWSProject.RWS.placeMailboxOrderResponse placeMailboxOrderResponse) {
            this.placeMailboxOrderResponse = placeMailboxOrderResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderSummaryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://websrvc.hss.integration.metcash.com/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SampleRWSProject.RWS.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.getOrderSummary getOrderSummary;
        
        public getOrderSummaryRequest() {
        }
        
        public getOrderSummaryRequest(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.getOrderSummary getOrderSummary) {
            this.authentication = authentication;
            this.getOrderSummary = getOrderSummary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderSummaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websrvc.hss.integration.metcash.com/", Order=0)]
        public SampleRWSProject.RWS.OrderSummaryResponse OrderSummaryResponse;
        
        public getOrderSummaryResponse() {
        }
        
        public getOrderSummaryResponse(SampleRWSProject.RWS.OrderSummaryResponse OrderSummaryResponse) {
            this.OrderSummaryResponse = OrderSummaryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IGAWebServicesChannel : SampleRWSProject.RWS.IGAWebServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GAWebServicesClient : System.ServiceModel.ClientBase<SampleRWSProject.RWS.IGAWebServices>, SampleRWSProject.RWS.IGAWebServices {
        
        public GAWebServicesClient() {
        }
        
        public GAWebServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GAWebServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GAWebServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GAWebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.RWS.areYouThereResponse1 SampleRWSProject.RWS.IGAWebServices.areYouThere(SampleRWSProject.RWS.areYouThereRequest request) {
            return base.Channel.areYouThere(request);
        }
        
        public SampleRWSProject.RWS.areYouThereResponse areYouThere(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.areYouThere areYouThere1) {
            SampleRWSProject.RWS.areYouThereRequest inValue = new SampleRWSProject.RWS.areYouThereRequest();
            inValue.authentication = authentication;
            inValue.areYouThere = areYouThere1;
            SampleRWSProject.RWS.areYouThereResponse1 retVal = ((SampleRWSProject.RWS.IGAWebServices)(this)).areYouThere(inValue);
            return retVal.areYouThereResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.RWS.downloadAllInvoicesResponse SampleRWSProject.RWS.IGAWebServices.downloadAllInvoices(SampleRWSProject.RWS.downloadAllInvoicesRequest request) {
            return base.Channel.downloadAllInvoices(request);
        }
        
        public SampleRWSProject.RWS.downloadAllInvoiceResponse downloadAllInvoices(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.downloadAllInvoice downloadAllInvoice) {
            SampleRWSProject.RWS.downloadAllInvoicesRequest inValue = new SampleRWSProject.RWS.downloadAllInvoicesRequest();
            inValue.authentication = authentication;
            inValue.downloadAllInvoice = downloadAllInvoice;
            SampleRWSProject.RWS.downloadAllInvoicesResponse retVal = ((SampleRWSProject.RWS.IGAWebServices)(this)).downloadAllInvoices(inValue);
            return retVal.downloadAllInvoiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.RWS.listInvoicesResponse SampleRWSProject.RWS.IGAWebServices.listInvoices(SampleRWSProject.RWS.listInvoicesRequest request) {
            return base.Channel.listInvoices(request);
        }
        
        public string[] listInvoices(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.listInvoices listInvoices1) {
            SampleRWSProject.RWS.listInvoicesRequest inValue = new SampleRWSProject.RWS.listInvoicesRequest();
            inValue.authentication = authentication;
            inValue.listInvoices = listInvoices1;
            SampleRWSProject.RWS.listInvoicesResponse retVal = ((SampleRWSProject.RWS.IGAWebServices)(this)).listInvoices(inValue);
            return retVal.listInvoicesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.RWS.listHostFilesQueuedResponse1 SampleRWSProject.RWS.IGAWebServices.listHostFilesQueued(SampleRWSProject.RWS.listHostFilesQueuedRequest request) {
            return base.Channel.listHostFilesQueued(request);
        }
        
        public SampleRWSProject.RWS.listHostFilesQueuedResponse listHostFilesQueued(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.listHostFilesQueued listHostFilesQueued1) {
            SampleRWSProject.RWS.listHostFilesQueuedRequest inValue = new SampleRWSProject.RWS.listHostFilesQueuedRequest();
            inValue.authentication = authentication;
            inValue.listHostFilesQueued = listHostFilesQueued1;
            SampleRWSProject.RWS.listHostFilesQueuedResponse1 retVal = ((SampleRWSProject.RWS.IGAWebServices)(this)).listHostFilesQueued(inValue);
            return retVal.listHostFilesQueuedResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.RWS.getLastFileSentResponse1 SampleRWSProject.RWS.IGAWebServices.getLastFileSent(SampleRWSProject.RWS.getLastFileSentRequest request) {
            return base.Channel.getLastFileSent(request);
        }
        
        public SampleRWSProject.RWS.getLastFileSentResponse getLastFileSent(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.getLastFileSent getLastFileSent1) {
            SampleRWSProject.RWS.getLastFileSentRequest inValue = new SampleRWSProject.RWS.getLastFileSentRequest();
            inValue.authentication = authentication;
            inValue.getLastFileSent = getLastFileSent1;
            SampleRWSProject.RWS.getLastFileSentResponse1 retVal = ((SampleRWSProject.RWS.IGAWebServices)(this)).getLastFileSent(inValue);
            return retVal.getLastFileSentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.RWS.getNextFileQueuedResponse SampleRWSProject.RWS.IGAWebServices.getNextFileQueued(SampleRWSProject.RWS.getNextFileQueuedRequest request) {
            return base.Channel.getNextFileQueued(request);
        }
        
        public SampleRWSProject.RWS.getFileResponse getNextFileQueued(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.getNextFileQueued getNextFileQueued1) {
            SampleRWSProject.RWS.getNextFileQueuedRequest inValue = new SampleRWSProject.RWS.getNextFileQueuedRequest();
            inValue.authentication = authentication;
            inValue.getNextFileQueued = getNextFileQueued1;
            SampleRWSProject.RWS.getNextFileQueuedResponse retVal = ((SampleRWSProject.RWS.IGAWebServices)(this)).getNextFileQueued(inValue);
            return retVal.getFileResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.RWS.placeMailboxOrderResponse1 SampleRWSProject.RWS.IGAWebServices.placeMailboxOrder(SampleRWSProject.RWS.placeMailboxOrderRequest request) {
            return base.Channel.placeMailboxOrder(request);
        }
        
        public SampleRWSProject.RWS.placeMailboxOrderResponse placeMailboxOrder(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.placeMailboxOrder placeMailboxOrder1) {
            SampleRWSProject.RWS.placeMailboxOrderRequest inValue = new SampleRWSProject.RWS.placeMailboxOrderRequest();
            inValue.authentication = authentication;
            inValue.placeMailboxOrder = placeMailboxOrder1;
            SampleRWSProject.RWS.placeMailboxOrderResponse1 retVal = ((SampleRWSProject.RWS.IGAWebServices)(this)).placeMailboxOrder(inValue);
            return retVal.placeMailboxOrderResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SampleRWSProject.RWS.getOrderSummaryResponse SampleRWSProject.RWS.IGAWebServices.getOrderSummary(SampleRWSProject.RWS.getOrderSummaryRequest request) {
            return base.Channel.getOrderSummary(request);
        }
        
        public SampleRWSProject.RWS.OrderSummaryResponse getOrderSummary(SampleRWSProject.RWS.Authentication authentication, SampleRWSProject.RWS.getOrderSummary getOrderSummary1) {
            SampleRWSProject.RWS.getOrderSummaryRequest inValue = new SampleRWSProject.RWS.getOrderSummaryRequest();
            inValue.authentication = authentication;
            inValue.getOrderSummary = getOrderSummary1;
            SampleRWSProject.RWS.getOrderSummaryResponse retVal = ((SampleRWSProject.RWS.IGAWebServices)(this)).getOrderSummary(inValue);
            return retVal.OrderSummaryResponse;
        }
    }
}
